export const SUPPORTED_PROVIDER_DATA = [
	{
		id: "302ai",
		name: "302.AI",
		env: ["302AI_API_KEY"],
		baseUrl: "https://api.302.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "abacus",
		name: "Abacus",
		env: ["ABACUS_API_KEY"],
		baseUrl: "https://routellm.abacus.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "alibaba",
		name: "Alibaba",
		env: ["DASHSCOPE_API_KEY"],
		baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "alibaba-cn",
		name: "Alibaba (China)",
		env: ["DASHSCOPE_API_KEY"],
		baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "alibaba-coding-plan",
		name: "Alibaba Coding Plan",
		env: ["ALIBABA_CODING_PLAN_API_KEY"],
		baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "alibaba-coding-plan-cn",
		name: "Alibaba Coding Plan (China)",
		env: ["ALIBABA_CODING_PLAN_API_KEY"],
		baseUrl: "https://coding.dashscope.aliyuncs.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "anthropic",
		name: "Anthropic",
		env: ["ANTHROPIC_API_KEY"],
		baseUrl: "https://api.anthropic.com",
		npm: "@ai-sdk/anthropic",
	},
	{
		id: "bailing",
		name: "Bailing",
		env: ["BAILING_API_TOKEN"],
		baseUrl: "https://api.tbox.cn/api/llm/v1/chat/completions",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "baseten",
		name: "Baseten",
		env: ["BASETEN_API_KEY"],
		baseUrl: "https://inference.baseten.co/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "berget",
		name: "Berget.AI",
		env: ["BERGET_API_KEY"],
		baseUrl: "https://api.berget.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "chutes",
		name: "Chutes",
		env: ["CHUTES_API_KEY"],
		baseUrl: "https://llm.chutes.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "clarifai",
		name: "Clarifai",
		env: ["CLARIFAI_PAT"],
		baseUrl: "https://api.clarifai.com/v2/ext/openai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "cloudferro-sherlock",
		name: "CloudFerro Sherlock",
		env: ["CLOUDFERRO_SHERLOCK_API_KEY"],
		baseUrl: "https://api-sherlock.cloudferro.com/openai/v1/",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "cortecs",
		name: "Cortecs",
		env: ["CORTECS_API_KEY"],
		baseUrl: "https://api.cortecs.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "deepseek",
		name: "DeepSeek",
		env: ["DEEPSEEK_API_KEY"],
		baseUrl: "https://api.deepseek.com",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "dinference",
		name: "DInference",
		env: ["DINFERENCE_API_KEY"],
		baseUrl: "https://api.dinference.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "drun",
		name: "D.Run (China)",
		env: ["DRUN_API_KEY"],
		baseUrl: "https://chat.d.run/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "evroc",
		name: "evroc",
		env: ["EVROC_API_KEY"],
		baseUrl: "https://models.think.evroc.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "fastrouter",
		name: "FastRouter",
		env: ["FASTROUTER_API_KEY"],
		baseUrl: "https://go.fastrouter.ai/api/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "fireworks-ai",
		name: "Fireworks AI",
		env: ["FIREWORKS_API_KEY"],
		baseUrl: "https://api.fireworks.ai/inference/v1/",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "firmware",
		name: "Firmware",
		env: ["FIRMWARE_API_KEY"],
		baseUrl: "https://app.frogbot.ai/api/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "friendli",
		name: "Friendli",
		env: ["FRIENDLI_TOKEN"],
		baseUrl: "https://api.friendli.ai/serverless/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "github-copilot",
		name: "GitHub Copilot",
		env: ["GITHUB_TOKEN"],
		baseUrl: "https://api.githubcopilot.com",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "github-models",
		name: "GitHub Models",
		env: ["GITHUB_TOKEN"],
		baseUrl: "https://models.github.ai/inference",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "google",
		name: "Google",
		env: ["GOOGLE_GENERATIVE_AI_API_KEY", "GEMINI_API_KEY"],
		baseUrl: "https://generativelanguage.googleapis.com",
		npm: "@ai-sdk/google",
	},
	{
		id: "groq",
		name: "Groq",
		env: ["GROQ_API_KEY"],
		baseUrl: "https://api.groq.com/openai/v1",
		npm: "@ai-sdk/groq",
	},
	{
		id: "helicone",
		name: "Helicone",
		env: ["HELICONE_API_KEY"],
		baseUrl: "https://ai-gateway.helicone.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "huggingface",
		name: "Hugging Face",
		env: ["HF_TOKEN"],
		baseUrl: "https://router.huggingface.co/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "iflowcn",
		name: "iFlow",
		env: ["IFLOW_API_KEY"],
		baseUrl: "https://apis.iflow.cn/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "inception",
		name: "Inception",
		env: ["INCEPTION_API_KEY"],
		baseUrl: "https://api.inceptionlabs.ai/v1/",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "inference",
		name: "Inference",
		env: ["INFERENCE_API_KEY"],
		baseUrl: "https://inference.net/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "io-net",
		name: "IO.NET",
		env: ["IOINTELLIGENCE_API_KEY"],
		baseUrl: "https://api.intelligence.io.solutions/api/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "jiekou",
		name: "Jiekou.AI",
		env: ["JIEKOU_API_KEY"],
		baseUrl: "https://api.jiekou.ai/openai",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "kilo",
		name: "Kilo Gateway",
		env: ["KILO_API_KEY"],
		baseUrl: "https://api.kilo.ai/api/gateway",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "kimi-for-coding",
		name: "Kimi For Coding",
		env: ["KIMI_API_KEY"],
		baseUrl: "https://api.kimi.com/coding/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "kuae-cloud-coding-plan",
		name: "KUAE Cloud Coding Plan",
		env: ["KUAE_API_KEY"],
		baseUrl: "https://coding-plan-endpoint.kuaecloud.net/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "llama",
		name: "Llama",
		env: ["LLAMA_API_KEY"],
		baseUrl: "https://api.llama.com/compat/v1/",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "llmgateway",
		name: "LLM Gateway",
		env: ["LLMGATEWAY_API_KEY"],
		baseUrl: "https://api.llmgateway.io/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "lmstudio",
		name: "LMStudio",
		env: ["LMSTUDIO_API_KEY"],
		baseUrl: "http://127.0.0.1:1234/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "lucidquery",
		name: "LucidQuery AI",
		env: ["LUCIDQUERY_API_KEY"],
		baseUrl: "https://lucidquery.com/api/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "meganova",
		name: "Meganova",
		env: ["MEGANOVA_API_KEY"],
		baseUrl: "https://api.meganova.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "minimax",
		name: "MiniMax (minimax.io)",
		env: ["MINIMAX_API_KEY"],
		baseUrl: "https://api.minimax.io/anthropic/v1",
		npm: "@ai-sdk/anthropic",
	},
	{
		id: "minimax-cn",
		name: "MiniMax (minimaxi.com)",
		env: ["MINIMAX_API_KEY"],
		baseUrl: "https://api.minimaxi.com/anthropic/v1",
		npm: "@ai-sdk/anthropic",
	},
	{
		id: "minimax-cn-coding-plan",
		name: "MiniMax Coding Plan (minimaxi.com)",
		env: ["MINIMAX_API_KEY"],
		baseUrl: "https://api.minimaxi.com/anthropic/v1",
		npm: "@ai-sdk/anthropic",
	},
	{
		id: "minimax-coding-plan",
		name: "MiniMax Coding Plan (minimax.io)",
		env: ["MINIMAX_API_KEY"],
		baseUrl: "https://api.minimax.io/anthropic/v1",
		npm: "@ai-sdk/anthropic",
	},
	{
		id: "mistral",
		name: "Mistral",
		env: ["MISTRAL_API_KEY"],
		baseUrl: "https://api.mistral.ai/v1",
		npm: "@ai-sdk/mistral",
	},
	{
		id: "mixlayer",
		name: "Mixlayer",
		env: ["MIXLAYER_API_KEY"],
		baseUrl: "https://models.mixlayer.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "moark",
		name: "Moark",
		env: ["MOARK_API_KEY"],
		baseUrl: "https://moark.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "modelscope",
		name: "ModelScope",
		env: ["MODELSCOPE_API_KEY"],
		baseUrl: "https://api-inference.modelscope.cn/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "moonshotai",
		name: "Moonshot AI",
		env: ["MOONSHOT_API_KEY"],
		baseUrl: "https://api.moonshot.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "moonshotai-cn",
		name: "Moonshot AI (China)",
		env: ["MOONSHOT_API_KEY"],
		baseUrl: "https://api.moonshot.cn/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "morph",
		name: "Morph",
		env: ["MORPH_API_KEY"],
		baseUrl: "https://api.morphllm.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "nano-gpt",
		name: "NanoGPT",
		env: ["NANO_GPT_API_KEY"],
		baseUrl: "https://nano-gpt.com/api/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "nebius",
		name: "Nebius Token Factory",
		env: ["NEBIUS_API_KEY"],
		baseUrl: "https://api.tokenfactory.nebius.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "nova",
		name: "Nova",
		env: ["NOVA_API_KEY"],
		baseUrl: "https://api.nova.amazon.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "novita-ai",
		name: "NovitaAI",
		env: ["NOVITA_API_KEY"],
		baseUrl: "https://api.novita.ai/openai",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "nvidia",
		name: "Nvidia",
		env: ["NVIDIA_API_KEY"],
		baseUrl: "https://integrate.api.nvidia.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "openai",
		name: "OpenAI",
		env: ["OPENAI_API_KEY"],
		baseUrl: "https://api.openai.com/v1",
		npm: "@ai-sdk/openai",
	},
	{
		id: "opencode",
		name: "OpenCode Zen",
		env: ["OPENCODE_API_KEY"],
		baseUrl: "https://opencode.ai/zen/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "opencode-go",
		name: "OpenCode Go",
		env: ["OPENCODE_API_KEY"],
		baseUrl: "https://opencode.ai/zen/go/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "openrouter",
		name: "OpenRouter",
		env: ["OPENROUTER_API_KEY"],
		baseUrl: "https://openrouter.ai/api/v1",
		npm: "@openrouter/ai-sdk-provider",
	},
	{
		id: "ovhcloud",
		name: "OVHcloud AI Endpoints",
		env: ["OVHCLOUD_API_KEY"],
		baseUrl: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "perplexity-agent",
		name: "Perplexity Agent",
		env: ["PERPLEXITY_API_KEY"],
		baseUrl: "https://api.perplexity.ai/v1",
		npm: "@ai-sdk/openai",
	},
	{
		id: "poe",
		name: "Poe",
		env: ["POE_API_KEY"],
		baseUrl: "https://api.poe.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "qihang-ai",
		name: "QiHang",
		env: ["QIHANG_API_KEY"],
		baseUrl: "https://api.qhaigc.net/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "qiniu-ai",
		name: "Qiniu",
		env: ["QINIU_API_KEY"],
		baseUrl: "https://api.qnaigc.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "requesty",
		name: "Requesty",
		env: ["REQUESTY_API_KEY"],
		baseUrl: "https://router.requesty.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "scaleway",
		name: "Scaleway",
		env: ["SCALEWAY_API_KEY"],
		baseUrl: "https://api.scaleway.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "siliconflow",
		name: "SiliconFlow",
		env: ["SILICONFLOW_API_KEY"],
		baseUrl: "https://api.siliconflow.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "siliconflow-cn",
		name: "SiliconFlow (China)",
		env: ["SILICONFLOW_CN_API_KEY"],
		baseUrl: "https://api.siliconflow.cn/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "stackit",
		name: "STACKIT",
		env: ["STACKIT_API_KEY"],
		baseUrl: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "stepfun",
		name: "StepFun",
		env: ["STEPFUN_API_KEY"],
		baseUrl: "https://api.stepfun.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "submodel",
		name: "submodel",
		env: ["SUBMODEL_INSTAGEN_ACCESS_KEY"],
		baseUrl: "https://llm.submodel.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "synthetic",
		name: "Synthetic",
		env: ["SYNTHETIC_API_KEY"],
		baseUrl: "https://api.synthetic.new/openai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "tencent-coding-plan",
		name: "Tencent Coding Plan (China)",
		env: ["TENCENT_CODING_PLAN_API_KEY"],
		baseUrl: "https://api.lkeap.cloud.tencent.com/coding/v3",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "the-grid-ai",
		name: "The Grid AI",
		env: ["THEGRIDAI_API_KEY"],
		baseUrl: "https://api.thegrid.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "upstage",
		name: "Upstage",
		env: ["UPSTAGE_API_KEY"],
		baseUrl: "https://api.upstage.ai/v1/solar",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "vivgrid",
		name: "Vivgrid",
		env: ["VIVGRID_API_KEY"],
		baseUrl: "https://api.vivgrid.com/v1",
		npm: "@ai-sdk/openai",
	},
	{
		id: "vultr",
		name: "Vultr",
		env: ["VULTR_API_KEY"],
		baseUrl: "https://api.vultrinference.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "wandb",
		name: "Weights & Biases",
		env: ["WANDB_API_KEY"],
		baseUrl: "https://api.inference.wandb.ai/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "xai",
		name: "xAI",
		env: ["XAI_API_KEY"],
		baseUrl: "https://api.x.ai/v1",
		npm: "@ai-sdk/xai",
	},
	{
		id: "xiaomi",
		name: "Xiaomi",
		env: ["XIAOMI_API_KEY"],
		baseUrl: "https://api.xiaomimimo.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "xiaomi-token-plan-ams",
		name: "Xiaomi Token Plan (Europe)",
		env: ["XIAOMI_API_KEY"],
		baseUrl: "https://token-plan-ams.xiaomimimo.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "xiaomi-token-plan-cn",
		name: "Xiaomi Token Plan (China)",
		env: ["XIAOMI_API_KEY"],
		baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "xiaomi-token-plan-sgp",
		name: "Xiaomi Token Plan (Singapore)",
		env: ["XIAOMI_API_KEY"],
		baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "zai",
		name: "Z.AI",
		env: ["ZHIPU_API_KEY"],
		baseUrl: "https://api.z.ai/api/paas/v4",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "zai-coding-plan",
		name: "Z.AI Coding Plan",
		env: ["ZHIPU_API_KEY"],
		baseUrl: "https://api.z.ai/api/coding/paas/v4",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "zenmux",
		name: "ZenMux",
		env: ["ZENMUX_API_KEY"],
		baseUrl: "https://zenmux.ai/api/v1",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "zhipuai",
		name: "Zhipu AI",
		env: ["ZHIPU_API_KEY"],
		baseUrl: "https://open.bigmodel.cn/api/paas/v4",
		npm: "@ai-sdk/openai-compatible",
	},
	{
		id: "zhipuai-coding-plan",
		name: "Zhipu AI Coding Plan",
		env: ["ZHIPU_API_KEY"],
		baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
		npm: "@ai-sdk/openai-compatible",
	},
] as const;
