export const compiledPackages = [
	{ dir: "packages/monopi__core", name: "@monopi/core" },
	{ dir: "packages/monopi__cli", name: "@monopi/cli" },
	{ dir: "packages/monopi__web-client", name: "@monopi/web-client" },
	{ dir: "packages/monopi__web-server", name: "@monopi/web-server" },
];

export const publishedPackages = [
	...compiledPackages,
	{
		dir: "packages/monopi__adaptive-routing",
		name: "@monopi/adaptive-routing",
	},
	{ dir: "packages/monopi__agents", name: "@monopi/agents" },
	{ dir: "packages/monopi__analytics-db", name: "@monopi/analytics-db" },
	{ dir: "packages/monopi__analytics-extension", name: "@monopi/analytics-extension" },
	{ dir: "packages/monopi__background-tasks", name: "@monopi/background-tasks" },
	{ dir: "packages/monopi__provider-cursor", name: "@monopi/provider-cursor" },
	{ dir: "packages/monopi__diagnostics", name: "@monopi/diagnostics" },
	{ dir: "packages/monopi__extension-answer", name: "@monopi/extension-answer" },
	{ dir: "packages/monopi__extension-watchdog", name: "@monopi/extension-watchdog" },
	{ dir: "packages/monopi__extension-bg-process", name: "@monopi/extension-bg-process" },
	{ dir: "packages/monopi__extension-btw", name: "@monopi/extension-btw" },
	{ dir: "packages/monopi__extension-compact-header", name: "@monopi/extension-compact-header" },
	{ dir: "packages/monopi__extension-custom-footer", name: "@monopi/extension-custom-footer" },
	{ dir: "packages/monopi__extension-external-editor", name: "@monopi/extension-external-editor" },
	{ dir: "packages/monopi__extension-git-guard", name: "@monopi/extension-git-guard" },
	{ dir: "packages/monopi__extension-scheduler", name: "@monopi/extension-scheduler" },
	{ dir: "packages/monopi__extension-shell-format", name: "@monopi/extension-shell-format" },
	{ dir: "packages/monopi__extension-tool-metadata", name: "@monopi/extension-tool-metadata" },
	{ dir: "packages/monopi__extension-usage-tracker", name: "@monopi/extension-usage-tracker" },
	{ dir: "packages/monopi__extension-worktree", name: "@monopi/extension-worktree" },
	{ dir: "packages/monopi__extension-shared", name: "@monopi/extension-shared" },
	{ dir: "packages/monopi__monopi", name: "@monopi/monopi" },
	{ dir: "packages/monopi__provider-ollama", name: "@monopi/provider-ollama" },
	{ dir: "packages/monopi__bash-live-view", name: "@monopi/bash-live-view" },
	{ dir: "packages/monopi__pretty", name: "@monopi/pretty" },
	{ dir: "packages/monopi__remote-tailscale", name: "@monopi/remote-tailscale" },
	{ dir: "packages/monopi__provider-catalog", name: "@monopi/provider-catalog" },
	{ dir: "packages/monopi__shared-qna", name: "@monopi/shared-qna" },
	{ dir: "packages/monopi__skills", name: "@monopi/skills" },
	{ dir: "packages/monopi__subagents", name: "@monopi/subagents" },
	{ dir: "packages/monopi__web-remote", name: "@monopi/web-remote" },
];
