export const compiledPackages = [
	{ name: "@ifi/oh-pi-core", dir: "packages/core" },
	{ name: "@ifi/oh-pi-cli", dir: "packages/cli" },
	{ name: "@ifi/pi-web-client", dir: "packages/web-client" },
	{ name: "@ifi/pi-web-server", dir: "packages/web-server" },
];

export const publishedPackages = [
	...compiledPackages,
	{ name: "@ifi/pi-extension-adaptive-routing", dir: "packages/adaptive-routing" },
	{ name: "@ifi/oh-pi-agents", dir: "packages/agents" },
	{ name: "@ifi/pi-analytics-db", dir: "packages/analytics-db" },
	{ name: "@ifi/pi-analytics-extension", dir: "packages/analytics-extension" },
	{ name: "@ifi/oh-pi-ant-colony", dir: "packages/ant-colony" },
	{ name: "@ifi/pi-background-tasks", dir: "packages/background-tasks" },
	{ name: "@ifi/pi-provider-cursor", dir: "packages/cursor" },
	{ name: "@ifi/pi-diagnostics", dir: "packages/diagnostics" },
	{ name: "@ifi/oh-pi-extensions", dir: "packages/extensions" },
	{ name: "@ifi/oh-pi", dir: "packages/oh-pi" },
	{ name: "@ifi/pi-provider-ollama", dir: "packages/ollama" },
	{ name: "@ifi/pi-bash-live-view", dir: "packages/pi-bash-live-view" },
	{ name: "@ifi/pi-pretty", dir: "packages/pi-pretty" },
	{ name: "@ifi/pi-remote-tailscale", dir: "packages/pi-remote-tailscale" },
	{ name: "@ifi/pi-plan", dir: "packages/plan" },
	{ name: "@ifi/oh-pi-prompts", dir: "packages/prompts" },
	{ name: "@ifi/pi-provider-catalog", dir: "packages/providers" },
	{ name: "@ifi/pi-shared-qna", dir: "packages/shared-qna" },
	{ name: "@ifi/oh-pi-skills", dir: "packages/skills" },
	{ name: "@ifi/pi-spec", dir: "packages/spec" },
	{ name: "@ifi/pi-extension-subagents", dir: "packages/subagents" },
	{ name: "@ifi/oh-pi-themes", dir: "packages/themes" },
	{ name: "@ifi/pi-web-remote", dir: "packages/web-remote" },
];
